### ISSUE TITLE
Tests against dandi-cli fail

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-schema#131]
https://github.com/dandi/dandi-schema/actions/runs/2187811011

**Comment by jwodder** [comment]
@yarikoptic The metadata conversion tests in dandi-cli are failing because the `repository` field in `BareAsset` isn't being defaulted to `https://dandiarchive.org/`, which happens because `DANDI_INSTANCE_URL` isn't set.  Note that the corresponding tests in the dandi-cli repository are passing because dandi-cli is still using dandischema 0.6.0.

**Comment by yarikoptic** [comment]
Cool, thanks for the explanation. Please submit a PR wherever it is due to set that `DJANGO_DANDI_WEB_APP_URL` env variable appropriately.
